### ISSUE TITLE
How to archive references to websites?

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#102]
I wonder how references to websites could be archived safely. Sofar we recommend copies to be stored on the supplementary CD/DVD (currently being replaced by a cloud archive). Specifically:
A) Which file format to use? 
* **Saving** to HTML+AuxFiles results in web pages that are usually incomplete (tried with Chrome and Firefox);
* Exporting to **PDF** introduces a page structure that does not exist in web pages.

B) Would it be better to use **links to archived snapshots**, e.g., instead of `` https://de.wikipedia.org/wiki/Reliquienschrein`` use ``https://web.archive.org/web/20121122130121/https://de.wikipedia.org/wiki/Reliquienschrein``?

**Comment by hochleitner** [comment]
The question I keep struggling with is, what exactly do we _need_ to save? Does it have to be an accurate representation of the website so that all the links and sub-pages are there as well and clickable, or is it enough if the relevant content (the one that's usually referenced) is readable and visible?

If it is the first, I think it is the best approach to use the Internet Archive's Wayback Machine (https://archive.org/web/), as you suggested. All provided that the site isn't taken down by this vast [lawsuit](https://www.theverge.com/2020/6/14/21290902/internet-archive-emergency-library-lawsuit).

If it's the latter, couldn't simple screenshots suffice? Why not just take some full-site PNGs and archive them? If you want it searchable, then go for PDFs. There are browser-addons such as [FireShot](https://getfireshot.com/) that can do this without much effort.

I get the need to preserve the current state of potentially volatile web-sources, but I think it's best not to overengineer the process.

**Comment by imagingbook** [comment]
IMHO it's the latter that we seek for. However. screenshots are a pain if the content does not fit on a single screen. I therefore recommend to use PDFs (as done already in the last update).

That lawsuit only applies to the emergency libary and should not affect the survival of the archive as whole. We should still consider this as an alternative ...

**Comment by hochleitner** [comment]
As mentioned, there are tools that can easily capture the whole page without the need for manual scrolling or stitching multiple screenshots. If the page is very long though, it will produce quite long graphics, there might also be issues with pages that have some sort of endless scrolling with JavaScript but I guess those are exceptions and our students can handle a graphics program should the need for manual stitching arise.

**Comment by rru-hgb** [comment]
In my experience, the links referenced typically point to a specific piece of written content on a web page (article, blog entry, etc.), therefore I consider a searchable pdf of that specific page to be a valuable substitute should the online version be gone. I don't think it is typically necessary to include subpages. The archive project is a valuable resource, but still, I would prefer to have access to an 'electronic hardcopy' of the referenced contents.

**Comment by imagingbook** [comment]
I am closing this issue because it is not technically relevant. I suppose PDF copies are the way to go and there seem to be plenty of methods to produce consistently looking and searchable PDFs of web pages for all browsers...
