### ISSUE TITLE
Not able to include Dockerfile-formatted code into program-listing

### ISSUE THREAD

**Issue by mrdextr** [Digital-Media/HagenbergThesis#104]
Hello!

I am currently writing my thesis and I am not able to include a Dockerfile as a code listing. Here you find the code I wanted to use:
```
\begin{program}
% place caption consistently either at the top or bottom:
  \caption{Test description}
  \label{prog:test}
  \begin{GenericCode}
FROM golang:alpine as builder RUN apk update && \
apk add git && \
CGO_ENABLED=0 go get ­a ­ldflags '­s' github.com/adriaandejonge/helloworld
FROM scratch
COPY ­­from=builder /go/bin/helloworld /helloworld EXPOSE 8080
CMD ["/helloworld"]
\end{GenericCode}
%
\end{program}
```

Could you please tell me how I can make it work? Or does the official thesis template need some extension to make this work?

all the best and thank you!

**Comment by imagingbook** [comment]
Your inserted code (no 'included Dockerfile' here) appears to contain illegal UTF-8 characters -- which LaTeX loudly complains about. Otherwise it works OK with GenericCode, as the attached PDF shows:

[Pages from main.pdf](https://github.com/Digital-Media/HagenbergThesis/files/5145041/Pages.from.main.pdf)
