### ISSUE TITLE
Infoboxes

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#109]
I'm using a macro called `infobox` in my lecture notes (that use the `hgbreport` class) for additional information.

```latex
\begin{infobox}[Bildformate im Web]
Im Web haben sich drei Bildformate für Pixelbilder etabliert, [...]
\end{infobox}
```

The output looks like this:

![infobox](https://user-images.githubusercontent.com/2236807/95594261-048b6000-0a4b-11eb-9488-8bad0330f8a0.png)

The code behind it uses the [mdframed](https://ctan.org/pkg/mdframed) package, so these boxes can also split up at page breaks. Colors and spacing can, of course, be adjusted; if the optional title argument is left out, the Box shows a generic "Infobox" header (but it could very well just be omitted).

Do we need this in our document?

Pros:
- It makes sense for lectures and informative material of the sorts.
- It's just a small macro that won't bloat the documents too much.

Cons:
- Another package dependency (`mdframed`).
- Students might (mis)use it in their theses. Not sure if something like this belongs in a thesis (can't think of a scenario right now).

@imagingbook: if you think this is useful, I can submit this as a PR. If not, just close the issue.

**Comment by imagingbook** [comment]
Nice feature (!) but I recommend not to include it to keep the footprint small (yes, still trying). While great for tutorials, lecture notes etc., I do not see much use for such boxes in a thesis and immediate abuse can be expected.
Nevertheless, since there are many cool packages around for one or the speciality, why not list/describe them in our Wiki, once they are tested and found to be compatible with (or adapted to) the hgb setup? I think this would be the best place and a valueable enhancement ...

**Comment by hochleitner** [comment]
Great Recommendation. I will write a wiki article on how to create such infoboxes.
