### ISSUE TITLE
Create an English edition

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#11]

**Comment by hochleitner** [comment]
Are you thinking of a completely separate edition or introducing a second chapter folder that has all the chapter in English?

**Comment by WilhelmBurger** [comment]
Still undecided. Probably a second chapters folder....

**Comment by WilhelmBurger** [comment]
This means a substantial step. If started, this should go along with a rigorous cleanup of the manuscript. Difficulty is to keep both versions in sync, would like to avoid mixed-language source files (due to bad experiences).

**Comment by WilhelmBurger** [comment]
Prepared the exsting structure for conversion to English, see here:
https://github.com/Digital-Media/HagenbergThesis/tree/wb-german-english

**Comment by hochleitner** [comment]
For computer software, [gettext](https://en.wikipedia.org/wiki/Gettext) is a widespread mechanism to do translations. You essentially mark the text that needs to be translated, have it exported to a .po File which can then be used in special translator software to make it easier and keep it uptodate. 
It seems like someone already implemented something like this for (La)TeX: https://github.com/mplucinski/tex-gettext
But since it makes use of XeTeX, I'm not sure if this is compatible with this template.

Concerning the new structure: Maybe it's a good idea to introduce `de` and `en` subdirectories in `chapters` in order to keep it cleaner?

**Comment by WilhelmBurger** [comment]
Ich bin mit der Struktur zZ auch nicht glücklich, gehe die alternative Variante grade durch. Leider hat Github die Handbremse angezogen ...



WB



________________________________

**Comment by imagingbook** [comment]
Directory structures for multiple languages have been set up in main branch/commit
https://github.com/Digital-Media/HagenbergThesis/commit/070812490417cf06baa8fb68f6a1c2d5efea8825

**Comment by hochleitner** [comment]
Since we've already put the split (DE/EN) into place I'll close this issue for now. I think the discussion about the extent of the content is something we should have elsewhere.

**Comment by krishnakumarg1984** [comment]
Is this usable for English-speaking countries now? I need to produce a PhD thesis at a US university (that has no template available and I am thinking of using this one)

**Comment by imagingbook** [comment]
Of course, and there are several examples in English. THIS issue is closed.
