### ISSUE TITLE
algpseudocodex missing in Overleaf

### ISSUE THREAD

**Issue by SydoxX** [Digital-Media/HagenbergThesis#122]
algpseudocodex is missing from the TeX Live version used by Overleaf resulting in a `LaTeX Error: File ``algpseudocodex.sty' not found.` error when trying to compile. Tested with HgbLabReportEN and HgbLabReportDE. 

Was introduced by #120

**Comment by hochleitner** [comment]
The issue is confirmed, thank you. Uploading `algpseudocodex.sty` to the Overleaf project fixes the issue (of course).

@imagingbook, to keep the current setup and avoid a rollback, I suggest including `algpseudocodex.sty` with our documents until Overleaf's server distro has picked up the file. This might only happen with the introduction of TeX Live 2021 on Overleaf. The planned release date for TeX Live 2021 is April 6th, so this might still take a few months until Overleaf switches to 2021. Unfortunately, there's no information if they are upgrading packages of current distros or not.

**Comment by imagingbook** [comment]
That's odd, according to CTAN `algpseudocodex` is contained in TeX Live 2020.
I will see how to fix this...

**Comment by imagingbook** [comment]
Commit https://github.com/Digital-Media/HagenbergThesis/commit/bf5ea5743a8207d1d9aa875a74df34759a3f469a fixes this issue by including `algpseudocodex.sty` in all document directories and associated ZIP files. A new directory `dev/latex-foreign` has been set up to (temporarily or permanently) hold style files from external packages that are not included in the standard TeX distributions. They are automatically copied by the (modified) `make` script.

**Comment by imagingbook** [comment]
@hochleitner Do you know if `algpseudocodex.sty` is still missing in Overleaf?

**Comment by hochleitner** [comment]
I'll test it to see if we can remove it from our files. I'll report back.

**Comment by imagingbook** [comment]
I just checked -- the problem persists!

**Comment by hochleitner** [comment]
Overleaf is still on TeX Live 2020 as I checked during an investigation for an issue with `acro` (see https://github.com/Digital-Media/HagenbergThesis/discussions/130). The problem will only get resolved when Overleaf upgraded to the 2020 distro. I'll monitor their blog closely.

**Comment by imagingbook** [comment]
Great. Yes, the make files need adaptation because `dev/latex-foreign/` will then be empty and this creates an error. Working on it already ...

**Comment by hochleitner** [comment]
Maybe you can adapt it so that it copies the files if something is in it and does nothing if it's empty? That way we can add files if necessary without editing the make files. But I guess you'll do it like this anyway? ;)

**Comment by imagingbook** [comment]
Yes, this is what I just did :-)
