### ISSUE TITLE
Title page of the English version is German

### ISSUE THREAD

**Issue by Heusini** [Digital-Media/HagenbergThesis#123]
The title page of the English version is in German

**Comment by hochleitner** [comment]
As our university requires a German cover page for all theses, no matter the actual language behind it, this is on purpose.

Should you require an English cover page, you have to adapt it in the cls file. It's not much of an effort though.

We have planned to make the cover page more flexible, but there's no ETA for that since it requires some bigger changes.

**Comment by Heusini** [comment]
Okay thanks. Thought it wasn't on purpose.
