### ISSUE TITLE
Replace $$ ... $$ with \[ ... \]

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#125]
The use of equations with `$$ ... $$` seems to be discouraged in LaTeX since it's a plain TeX command. It can obviously break stuff as mentioned in the following sources:

- https://mirror.easyname.at/ctan/info/l2tabu/german/l2tabu.pdf, section 1.6
- https://tex.stackexchange.com/questions/503/why-is-preferable-to

Reading this I'd say we replace the part in `mathematik.tex` of the tutorial with the LaTeX friendly syntax, although I'm too little of a LaTeX math expert to say if there are any implications. I did a quick test and didn't see any changes. @imagingbook, could you confirm this?

Also, `\( ... \)` should then probably used instead of `$ ... $` although there is definitely the case of readability that favors the dollar signs. 

There are some pros and cons mentioned here: https://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode. I'm not sure though if most of the things are relevant to our documents.

**Comment by imagingbook** [comment]
Reading this (which I did before) I'd say that they never really come forward with a good reason for replacing `$ ... $` by `\( ... \)`. Anyone is free to declare "deadly sins", but this one is unreasonable from my point. I strongly suggest to keep the old `$...$` scheme simply because it is easier to type and read. Also, some editors do not seem to syntax-highlight properly with `\( ... \)`.
For displayed math I have no objections to change, since we use the AMS package anyways.

**Comment by hochleitner** [comment]
Closed with commit a971702.
