### ISSUE TITLE
Include DOI in references

### ISSUE THREAD

**Issue by hochleitner** [Digital-Media/HagenbergThesis#146]
People in our department, notably @schedldave, requested that we include DOIs in the references. They are standardized and way shorter than URLs (especially long and ugly ones to sites like Research Gate), and Biblatex converts them to a clickable URL nicely.

I do support this because it makes digitally reviewing a thesis easier. One does not need to search for a referenced paper but can access it through the DOI. Yet it does not blow up entries as any arbitrary URL could do.

The only issue is that most exporter citations (from ACM, IEEE and the like) tend to have a `doi` and an `url` field set (which contains the DOI URL). This creates reference entries with the DOI appearing twice. To counter this, I suggest adding a rule to `hgbbib.sty` that goes through the items and clears the `url` entry when `doi` is present. Something like this (inspired from [here](https://tex.stackexchange.com/questions/381491/biblatex-numeric-comp-suppress-doi-and-url-for-journals-unless-the-article)) should do the trick:

```latex
\AtEveryBibitem{
    \iffieldundef{doi}{}{\clearfield{url}}
}
```

If necessary, we can limit this to specific bib types, but I can't think of anything where a DOI and an URL are both required.

**Comment by schedldave** [comment]
+1

In the `hgbbib.sty` the following changes are necessary: 
```latex
\ExecuteBibliographyOptions{
	bibencoding=auto,
	bibwarn=true,
	sortcites=true,
	defernumbers=true,
	isbn=false,
	doi=true, % CHANGED!
	backref=true,
	backrefstyle=three}

% ADDED remove URL if DOI is given
\AtEveryBibitem{
    \iffieldundef{doi}{}{\clearfield{url}}
}
```

I tested it very roughly here: https://github.com/schedldave/thesis-doi/
For articles with URLs and DOIs it leads to nice results:
![image](https://user-images.githubusercontent.com/1815472/209943900-0f1a6d2b-14e4-474b-a9e4-c9b16c66b1d5.png)


The main effort will be to update all existing example references, as there are no DOIs right now.

**Comment by hochleitner** [comment]
Thanks for the input. I'll create a PR with the necessary changes and updated references. You're welcome to review it alongside @imagingbook.

**Comment by imagingbook** [comment]
I think it is generally a good idea to promote the use of DOIs (in contrast to what our manual currently suggests) and the proposed URL removal rule seems to be a viable compromise. However, I do not see the need to convert "all existing example references" since **(a)** no DOIs may exist for many of them and **(b)** a traditional reference _without_ a DOI (although perhaps available) should still be fully acceptable. So let's go ahead with this.
One note of caution about citation "exporters" though: They are notoriously unreliable, i.e., their output is usually messed up in one or the other way. In fact, I don't think I have _ever_ downloaded a single bibtex item from any of the big publishers which I found 1:1 acceptable and did not have to manually edit afterwards. What I am saying is that it is still the final responsibility of the (thesis) authors to check that entries are complete and correct.
