### ISSUE TITLE
Links to files in FileList environment not working correctly

### ISSUE THREAD

**Issue by hlorenz** [Digital-Media/HagenbergThesis#38]
One would expect that when clicking on e.g. "vorwort.tex" in
```latex
\begin{FileList}{/thesis_DE/front}
\fitem{vorwort.tex} Vorwort %
\fitem{kurzfassung.tex} Kurzfassung %
\fitem{abstract.tex} Abstract %
\end{FileList}
```
would link to the file `/thesis_DE/front/vorwort.tex`, but instead it links to `/vorwort.tex`.
Maybe this is intended, I don't know, but I thought it is worth mentioning here.

I tested this with the current PDF version of this repository.

PS: This code excerpt is from the file `thesis_DE/back/anhang_b.tex`

**Comment by hochleitner** [comment]
Hi @hlorenz,

this is definitely not ideal and happened when the directory structure was changed. The `FileList` environment and `\fitem` command do not reflect this. I'll look into it though it's a bit tricky since the `\fitem` command will need to access the parameter that's been passed on to the `FileItem` environment in order to prepend the correct path.

**Comment by imagingbook** [comment]
The paths provided by ``\fitem`` were actually never intended to be opened from the PDF, ``\url{}`` was only used for formatting reasons. I suggest to use ``\nolinkurl`` instead.

**Comment by imagingbook** [comment]
Fixed by using \nolinkurl (files are not linked).
