### ISSUE TITLE
Fresh Thesis build fails

### ISSUE THREAD

**Issue by myieye** [Digital-Media/HagenbergThesis#57]
Fresh copies of HgbThesisTutorial, HgbThesisDE or HgbThesisEN do not build.
![image](https://user-images.githubusercontent.com/12587509/31884063-3d1def1e-b7ec-11e7-9a55-8c8ae06a6902.png)

**Comment by imagingbook** [comment]
Strange bug, did not reproduce in MikTeX. Apparently caused by removing dates in optional arguments of ``\ProvidesClass`` in ``.cls`` files. Temporarily solved by commenting them out (as suggested in https://tex.stackexchange.com/questions/305535/custom-book-class-providesclass-command and others).
@myieye pls test again.

**Comment by imagingbook** [comment]
Ahh, the optional argument to ``\ProvidesClass`` **must** start with a proper date, such as ``\ProvidesClass{classname}[2017/02/27 notes]``! Shit really happens ...
