### ISSUE TITLE
list of listings is not working.

### ISSUE THREAD

**Issue by ppey** [Digital-Media/HagenbergThesis#61]
When i use the program enviroment like:
```
\begin{program}[ht]
\begin{CppCode}[firstnumber=668]
#if defined(__arm__)
#elif defined(__x86_64__)
#endif
\end{CppCode}
\caption{foo bar batz}
\label{prog:mylabel}
\end{program}
```
i would like to have list of these listings, just like a list figures. Unfortunately using ```\lstlistoflistings ``` just creates an empty page. How can i work around that?
Thanks!

**Comment by hochleitner** [comment]
This happens since our template uses the `\lstnewenvironment` command to create separate environments for each language (as opposed to creating general listings using `\begin{lstlisting} ... \end{lstlisting}`.
For this to work, our environments need to specify the `caption` parameter that names the listing. Since captions in our template are passed via the `\caption` macro, the list of listing obviously doesn't process theses so it has nothing to use as a title and leaves the entry blank.

We'll have to look into this to see if we can set this parameter automatically with the contents of `\caption`. Otherwise it most likely means redefining the way, captions are defined (e.g. as an optional argument with the enivornment name) and this would have a huge influence on backwards compatibility.

**Comment by hochleitner** [comment]
@ppey I think for now, the much simpler solution is to use the following command: `\listof{program}{List of Programs}`

That gives you a list of all the floating `program` environments with the respective caption used.

**Comment by ppey** [comment]
> ``\listof{program}{List of  of Programs} ``

works fine! Thanks for your help!
