### ISSUE TITLE
Supplementary electronic media / web archiving

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#89]
The thesis tutorial mentions USB sticks as an option for supplementary electronic media -- remove, only CD/DVD is currently accepted.

Referenced websites often disappear quickly, making screenshots (and storing on electronic media) is desirable but tedious. Alternatively, let's look into online web archiving services, such as

- https://archive.today/
- https://webcitation.org/ (ironically, this site is itself dead at the moment!, see https://en.wikipedia.org/wiki/WebCite)

See also https://en.wikipedia.org/wiki/List_of_Web_archiving_initiatives

**Comment by hochleitner** [comment]
What about https://figshare.com/? This seems like the sort of research management system that could be useful. Either for putting the final PDF online as well as the support materials.
It might even be useful for our R&D department, since there is an institutional approach as well: https://knowledge.figshare.com/institutions (the video here describes it quite well).

**Comment by imagingbook** [comment]
This question has been resolved at least for Hagenberg: supplementary materials must be uploaded to the school's cloud store. No more CD/DVDs ...

**Comment by imagingbook** [comment]
TO DO: Remove/adapt all mentionings of CD/DVD-supplied data in the thesis tuitorial!
