### ISSUE TITLE
Bachelor thesis: no associated course any more!

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#92]
In Austria, a FH-Bachelor thesis is not associated with a specific course ("Lehrveranstaltung") any longer (by law). Title pages should thus be modified accordingly.

**Comment by imagingbook** [comment]
@hochleitner : I suggest to remove all parameters that are specific to a Bachelor thesis. That is, Bachelor and Master theses will basically look the same. OK?

**Comment by hochleitner** [comment]
Yeah, makes total sense. I always liked the supervisor field and actually think it might make sense for masters theses as well. Same goes for the copyright statement - why not use this for bachelors theses as well? We could then simplify the covers so that only the word "BACHELORARBEIT/MASTERARBEIT" needs to be different.

**Comment by imagingbook** [comment]
Agreed. I suggest to make the ``\advisor{..}`` entry optional. If not defined, the "advisor page" simply does not appear.

**Comment by imagingbook** [comment]
This is implemented in branch ``bachelor-no-course`` now and ready to be pulled. 
**TODO:** Internship reports are no bachelor theses any longer, needs to be fixed!

**Comment by imagingbook** [comment]
Completed with PR #93. Thesis Tutorial and Manual have been updated accordingly.
@hochleitner : Pls. check occasionally for omissions.
