### ISSUE TITLE
Multiple citations not properly sorted

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HagenbergThesis#96]
Multiple citations are not properly sorted when they include references from *different* categories, as in this example (from ``HgbThesisTutorial/literatur.tex``):
````
Interessant sind auch \cite{Nosferatu1922,BurgeBurger1999,Patashnik1988,Duden1997}.
````
The corresponding reference numbers are 37, 5, 30, 15 (with 5-30 in one category, 37 in another). The rendered result is `` Interessant sind auch [5, 15, 37, 30].``

**Comment by hochleitner** [comment]
This is due to Biblatex's sorting settings and the lack of an author for the Nosferatu entry. The `sorting` argument of Biblatex (see section 3.1.2.1 of the manual) uses `nty` - name, title, year as a default.
Given the four entries above we get Burger, Friedrich, Nosferatu (no author, so the title is taken) and Patashnik. Rename Nosferatu to e.g. "Zosferatu" (so that it's sorted after Patashnik), you get the seemingly correct order of [5, 15, 30, 37].
Conversely, when adding an author to the Nosferatu entry, e.g. `author={Aal, Albert}`, the entry is being sorted at the very front and we get [35, 5, 15, 30].

So the cite command (due to the `sortcites=true` option) does it's own, absolute sorting not based on the numbers but on the global sorting scheme.

This has been discussed as a GitHub issue for Biblatex here in 2016 (!): https://github.com/plk/biblatex/issues/491. Unfortunately, nothing "simple" has come of it. There are follow-up links to tex.stackexchange (this one has the links to all of them in it: https://tex.stackexchange.com/questions/332234/biblatex-citation-sorting-with-split-bibliographies-and-filters) where there are at least working solutions for this issue, e.g. creating a source map that gives the cite command to sort by the numbers assigned by Biblatex.

Question is, do we want to implement one of these? They are all in a way just workarounds.

**Comment by hochleitner** [comment]
Opened a pull request in the dev repository that should fix this issue.

**Comment by imagingbook** [comment]
Looks good, there was only a typo ("sofware") in the .sty file, which I fixed. Guess this is ready to be pulled.​
