### ISSUE TITLE
Multiple authors

### ISSUE THREAD

**Issue by GerritPlehn** [Digital-Media/HagenbergThesis#98]
When trying to set multiple authors with `\and` according to the [documentation](http://tug.ctan.org/tex-archive/info/latex2e-help-texinfo/latex2e.html#g_t_005cmaketitle), `\maketitle` times out on overleaf and my local installation does not finish either.

Overleaf provides the following errors:
```! Misplaced \crcr.
\endtabular ->\crcr 
                    \egroup \egroup $\egroup 
l.50 \maketitle
               
I can't figure out why you would want to use a tab mark
or \cr or \span just now. If something like a right brace
up above has ended a previous alignment prematurely,
you're probably due for more error messages, and you
might try typing `S' now just to see what is salvageable.

! Extra }, or forgotten \endgroup.
\endtabular ->\crcr \egroup \egroup 
                                    $\egroup 
l.50 \maketitle
               
I've deleted a group-closing symbol because it seems to be
spurious, as in `$x}$'. But perhaps the } is legitimate and
you forgot something else, as in `\hbox{$x}'. In such cases
the way to recover is to insert both the forgotten and the
deleted material, e.g., by typing `I$}'.

! Extra }, or forgotten $.
<recently read> \egroup 
                        
l.50 \maketitle
               
I've deleted a group-closing symbol because it seems to be
spurious, as in `$x}$'. But perhaps the } is legitimate and
you forgot something else, as in `\```

**Comment by hochleitner** [comment]
Which class/document did you use?

**Comment by GerritPlehn** [comment]
> Which class/document did you use?

`\documentclass[internship,german,smartquotes]{hgbthesis}`

**Comment by imagingbook** [comment]
The `hgbthesis` class redefines the `maketitle` command to create custom title pages and does not support the `\and` syntax of LaTeX's standard document classes. The assumption is that a thesis always has a single author, thus there is no provision for multiple authors in this case. As a quick remedy you could simply use `and` instead of `\and` between authors.
However, the classes `hgbarticle` and `hgbreport` use the standard `maketitle` command and also support multiple authors as usual (e.g., see the examples `HgbArticle` and `HgbLabReportEN`).

**Comment by imagingbook** [comment]
As a quick fix, `hgbthesis.cls` now issues a package warning if trying to define multiple authors inside the `\author{..}` command. The `\and` and `\thanks{..}` commands are suppressed. This at least stops LaTeX from hanging indefinitely ...
